### ISSUE TITLE
`NoneType` object has no attribute 'latitude'

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AffidavitofIndigencyMAVC#26]
```
There was an error in the Suffolk Lit Lab-Prod application.

The error message was:

AttributeError: 

    AttributeError: 'NoneType' object has no attribute 'latitude'



Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7642, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8984, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 4, in 
NameError: name 'ask_affidavit_questions' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8372, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8984, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 22, in 
NameError: name 'tried_geolocating' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7589, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7923, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7712, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking,
                                                   follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8489, in askfor
    question_result = self.askfor(newMissingVariable, user_dict, old_user_dict, interview_status, variable_stack=variable_stack,
                                                  questions_tried=questions_tried, seeking=seeking, follow_mc=follow_mc, 
                                                  recursion_depth=recursion_depth, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8372, in askfor
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8984, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "", line 1, in 
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/util.py", line 1469, in geolocate
    return self.geocode(address=address, reset=reset)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/util.py", line 1521, in geocode
    self.location.latitude = geocoder.data.latitude
AttributeError: 'NoneType' object has no attribute 'latitude'

The referer URL was https://apps.suffolklitlab.org/run/indigency/
```

**Comment by nonprofittechy** [comment]
I think we should bite the bullet and point to the form that is on AssemblyLine and remove the MAVC version.

**Comment by BryceStevenWilley** [comment]
Note that we have since moved the standalone form to the AssemblyLine version, and not the MAVC version.

I'll mark this issue as won't fix
